### ISSUE TITLE
product.model.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [IgorPonomarenko/AngularTraining#4]
export class Product implements Item {
  constructor(
    public name: string,
    public description: string,
    public price: number,
    public category: string,
    public isAvailable: boolean
  ) {
    // Этот код не нужен. Создание свойств и их инициализация и так произойдет, так как для параметров конструктора используется модификатор доступа public
    //this.name = name;
    //this.description = description;
    //this.price = price;
    //this.category = category;
    //this.isAvailable = isAvailable;
  }
}

**Comment by IgorPonomarenko** [comment]
noted
