### ISSUE TITLE
inventory.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [IgorPonomarenko/AngularTraining#5]
import {Product} from "./product.model";
Я в будущих версиях воркшопа планирую перейти на именование моделей так
Product => ProductModel - добавлю суффикс. Может букв и больше, но читаемость такой строчки повышается
import {ProductModel} from "./product.model";
По аналогии
import { ProductComponent } from './product.component'
Но решать вам хотите или нет следовать такому именованию

**Comment by IgorPonomarenko** [comment]
согласен
