### ISSUE TITLE
index.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [IgorPonomarenko/AngularTraining#7]
export * from './components/cart-item/cart-item.component';
export * from './services/cart-service/cart.service';

//TODO Circular dependency when using index.ts file. Don't know how to avoid it

Если выс оздали файл, то его должны использовать сущности которые ссылаются на эту папку, но не сущности из этой папки и тогда не будет циклических зависимостей.

**Comment by IgorPonomarenko** [comment]
Thanks, noted.
